repository:	     mecid/mecid.github.io
# Permalinks
permalink:           /:year/:month/:day/:title/

# Setup
theme: minima
title:               Dinesh Kachhot
url:                 https://dineshkachhot.github.io
paginate:            10
baseurl:             ""
analytics_id:        UA-18491817-18

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Dinesh Kachhot
  url:               https://twitter.com/DineshKachhot
  email:             dinesh.kachhot@gmail.com

# Gems
plugins:
  - jekyll-avatar
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
